name: Plex Watch Check

on:
  workflow_dispatch:  # Manual trigger for the workflow

jobs:
  check-plex-watch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install axios
        run: npm install axios  # Install axios directly without package.json

      - name: Run Plex Watch Script
        run: node js/plex-watch-script.js
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          PLEX_SERVER_URL: ${{ secrets.PLEX_SERVER_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit changes to last_watched.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add last_watched.json  # Only add the specific file you want to commit
          git commit -m "Update last watched item"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for commit permissions
